version: "3.9"
services: 
  prometheus:
    build: ./prometheus/
    ports: 
      - "9090:9090"
    restart: always
  
  grafana: 
    build: ./grafana/
    ports: 
      - "3000:3000"
    restart: always

  mysql:
    build: ./mysql/
    ports: 
      - "3306:3306"
    restart: always
    volumes: 
      - "/home/ubuntu/nuskusa-infra/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 8080:8080