name: Docker Image CI/CD

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ap-southeast-1
            -   uses: actions/checkout@v2
            -   id: CodeDeploy
                uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
                with:
                    application: nuskusa
